-- Run inside BEGIN/ROLLBACK. All fixtures use reserved .invalid domains.
create temp table le_test_results(name text primary key,passed boolean not null);
create function pg_temp.le_assert(n text,ok boolean) returns void language plpgsql as $$ begin
 if ok is distinct from true then raise exception 'ASSERTION FAILED: %',n; end if;
 insert into le_test_results values(n,true);
end $$;
do $$
declare p jsonb; a jsonb; b jsonb; c uuid; c2 uuid; route uuid; l uuid; m uuid; batch uuid; reservation uuid; job jsonb; same jsonb; before_count int; rec uuid; tmp uuid; denied boolean;
begin
 p:='{"source":"__le_test","external_id":"company-1","source_url":"https://alpha.invalid","company_name":"Test Alpha","website":"https://alpha.invalid","kvk":"12345678","niche":"schilder","country":"NL","active_status":"ACTIVE"}';
 a:=public.le_command('ingest',p); c:=(a->>'company_id')::uuid;
 b:=public.le_command('ingest',p);
 perform pg_temp.le_assert('import replay preserves company and source record',a->>'company_id'=b->>'company_id' and a->>'source_record_id'=b->>'source_record_id' and (b->>'replayed')::boolean);
 b:=public.le_command('ingest',p||'{"source":"__le_second_source","external_id":"other-id"}');
 perform pg_temp.le_assert('cross-source company dedup',b->>'company_id'=c::text and (select count(*)=1 from lead_engine.companies where domain='alpha.invalid'));
 b:=public.le_command('ingest',p||'{"external_id":"conflict","kvk":"87654321"}');
 perform pg_temp.le_assert('conflicting KVK quarantined',(b->>'status')='REVIEW' and not b ? 'company_id');
 b:=public.le_command('ingest',p||'{"company_name":"Unreviewed source rename"}');
 perform pg_temp.le_assert('import does not overwrite canonical company',(select name='Test Alpha' from lead_engine.companies where id=c));
 perform public.le_command('correct_company',jsonb_build_object('company_id',c,'source_url','https://alpha.invalid','reviewer','test','reason','confirmed city','fields',jsonb_build_object('city','Enschede')));
 perform pg_temp.le_assert('manual correction is auditable',exists(select 1 from lead_engine.observations where company_id=c and layer='MANUAL_CORRECTION'));
 route:=(public.le_command('contact',jsonb_build_object('company_id',c,'kind','EMAIL','value',' Info@Alpha.invalid ','source_url','https://alpha.invalid/contact','is_role_mailbox',true))->>'route_id')::uuid;
 l:=(public.le_command('create_list','{"name":"Test list","purpose":"EXPLORATION","niche":"schilder","selection_logic":{"hypothesis":"pilot"}}')->>'list_id')::uuid;
 a:=public.le_command('build_list',jsonb_build_object('list_id',l));
 perform pg_temp.le_assert('list build creates traceable member',(a->>'added')::int=1 and exists(select 1 from lead_engine.build_runs where list_id=l and status='SUCCEEDED'));
 select id into m from lead_engine.list_members where list_id=l and company_id=c;
 a:=public.le_command('gate',jsonb_build_object('member_id',m));
 perform pg_temp.le_assert('unverified contact blocked',not (a->>'allowed')::boolean and a->'reasons' ? 'EMAIL_NOT_VERIFIED_VALID');
 perform public.le_command('qualify',jsonb_build_object('member_id',m,'status','APPROVED','source_url','https://alpha.invalid','reviewer','test'));
 perform public.le_command('verification',jsonb_build_object('route_id',route,'status','valid','verifier','TEST_FIXTURE','evidence_ref','test://valid'));
 a:=public.le_command('gate',jsonb_build_object('member_id',m));
 perform pg_temp.le_assert('verified role mailbox allowed',(a->>'allowed')::boolean);
 update public.email_verifications set checked_at=now()-interval '20 days' where normalized_email='info@alpha.invalid';
 a:=public.le_command('gate',jsonb_build_object('member_id',m));
 perform pg_temp.le_assert('stale verification blocked',a->'reasons' ? 'VERIFICATION_STALE');
 update public.email_verifications set checked_at=now(),verification_status='catch_all' where normalized_email='info@alpha.invalid';
 a:=public.le_command('gate',jsonb_build_object('member_id',m));
 perform pg_temp.le_assert('catch-all blocked',a->'reasons' ? 'EMAIL_NOT_VERIFIED_VALID');
 update public.email_verifications set verification_status='valid',is_catch_all=true where normalized_email='info@alpha.invalid';
 a:=public.le_command('gate',jsonb_build_object('member_id',m));
 perform pg_temp.le_assert('contradictory catch-all flag blocked',a->'reasons' ? 'EMAIL_NOT_VERIFIED_VALID');
 update public.email_verifications set is_catch_all=false where normalized_email='info@alpha.invalid';
 perform public.le_command('ready_list',jsonb_build_object('list_id',l));
 batch:=(public.le_command('create_batch',jsonb_build_object('list_id',l,'name','Test batch','campaign_id','test-campaign'))->>'batch_id')::uuid;
 denied:=false; begin perform public.le_command('reserve',jsonb_build_object('member_id',m,'batch_id',batch)); exception when raise_exception then denied:=true; end;
 perform pg_temp.le_assert('unapproved batch blocked',denied);
 perform public.le_command('approve_batch',jsonb_build_object('batch_id',batch,'reviewer','test'));
 a:=public.le_command('reserve',jsonb_build_object('member_id',m,'batch_id',batch)); reservation:=(a->>'reservation_id')::uuid;
 perform pg_temp.le_assert('approved member reserved atomically',reservation is not null and exists(select 1 from lead_engine.outbox where reservation_id=reservation));
 b:=public.le_command('reserve',jsonb_build_object('member_id',m,'batch_id',batch));
 perform pg_temp.le_assert('reservation replay idempotent',b->>'reservation_id'=reservation::text and (select count(*)=1 from lead_engine.outbox where reservation_id=reservation));
 batch:=(public.le_command('create_batch',jsonb_build_object('list_id',l,'name','Conflicting batch'))->>'batch_id')::uuid;
 perform public.le_command('approve_batch',jsonb_build_object('batch_id',batch,'reviewer','test'));
 a:=public.le_command('reserve',jsonb_build_object('member_id',m,'batch_id',batch));
 perform pg_temp.le_assert('second active company blocked',a->'reasons' ? 'ACTIVE_OUTREACH_CONFLICT');
 a:=public.le_command('prepare_dispatch',jsonb_build_object('outbox_id',(select id from lead_engine.outbox where reservation_id=reservation)));
 perform pg_temp.le_assert('unconfigured outbound cannot dispatch',not (a->>'allowed')::boolean);
 insert into public.email_suppressions(email,reason,source) values('info@alpha.invalid','unsubscribe','TEST_FIXTURE');
 update lead_engine.settings set value='true' where key='outreach_enabled';
 update lead_engine.integrations set status='AVAILABLE' where name='smartlead';
 a:=public.le_command('prepare_dispatch',jsonb_build_object('outbox_id',(select id from lead_engine.outbox where reservation_id=reservation)));
 perform pg_temp.le_assert('late unsubscribe blocks dispatch',not (a->>'allowed')::boolean and (select status='CANCELLED' from lead_engine.outbox where reservation_id=reservation));
 update lead_engine.settings set value='false' where key='outreach_enabled';
 update lead_engine.integrations set status='NOT_CONFIGURED' where name='smartlead';
 a:=public.le_command('ingest','{"source":"__le_test","external_id":"company-2","source_url":"https://beta.invalid","company_name":"Test Beta","website":"https://beta.invalid","niche":"schilder","country":"NL","active_status":"ACTIVE"}');c2:=(a->>'company_id')::uuid;
 denied:=false; begin insert into lead_engine.list_members(list_id,company_id,route_id,selection_reason,selection_snapshot) values(l,c2,route,'bad relation','{}'); exception when foreign_key_violation then denied:=true; end;
 perform pg_temp.le_assert('cross-company route rejected',denied);
 job:=public.le_command('claim_job','{"worker":"test-worker","kinds":["WEBSITE_AUDIT"]}');
 same:=public.le_command('claim_job','{"worker":"test-worker-2","kinds":["WEBSITE_AUDIT"]}');
 perform pg_temp.le_assert('claimed job not claimed again',job->>'id'<>same->>'id');
 denied:=false; begin perform public.le_command('finish_job',jsonb_build_object('job_id',job->>'id','lease_token',gen_random_uuid(),'outcome','SUCCEEDED')); exception when raise_exception then denied:=true; end;
 perform pg_temp.le_assert('incorrect lease token rejected',denied);
 a:=public.le_command('finish_job',jsonb_build_object('job_id',job->>'id','lease_token',job->>'lease_token','outcome','RETRY','error_code','TIMEOUT'));
 perform pg_temp.le_assert('transient failure retries later',a->>'status'='RETRY_WAIT' and exists(select 1 from lead_engine.jobs where id=(job->>'id')::uuid and run_after>now()));
 update lead_engine.jobs set lease_until=now()-interval '1 second' where id=(same->>'id')::uuid;
 a:=public.le_command('recover_jobs');
 perform pg_temp.le_assert('expired worker recovered',(a->>'recovered')::int=1);
 denied:=false; begin perform public.le_command('finish_job',jsonb_build_object('job_id',same->>'id','lease_token',same->>'lease_token','outcome','SUCCEEDED')); exception when raise_exception then denied:=true; end;
 perform pg_temp.le_assert('expired worker cannot commit late output',denied);
 update lead_engine.jobs set run_after=now(),max_attempts=attempt_count+1 where id=(job->>'id')::uuid;
 job:=public.le_command('claim_job','{"worker":"test-worker","kinds":["WEBSITE_AUDIT"]}');
 a:=public.le_command('finish_job',jsonb_build_object('job_id',job->>'id','lease_token',job->>'lease_token','outcome','RETRY','error_code','TIMEOUT'));
 perform pg_temp.le_assert('retry limit creates visible failure',a->>'status'='FAILED' and exists(select 1 from lead_engine.incidents where dedup_key='job:'||(job->>'id')));
 p:=jsonb_build_object('provider','TEST','external_event_id','reply-1','reservation_id',reservation,'event_type','POSITIVE');
 a:=public.le_command('outcome',p); b:=public.le_command('outcome',p);
 perform pg_temp.le_assert('duplicate outcome processed once',(b->>'replayed')::boolean and (select count(*)=1 from lead_engine.outcomes where provider='TEST' and external_event_id='reply-1'));
 perform pg_temp.le_assert('positive outcome creates one CRM handoff',a->>'opportunity_id'=b->>'opportunity_id' and exists(select 1 from lead_engine.crm_handoffs where reservation_id=reservation));
 denied:=false; begin perform public.le_command('outcome',p||'{"event_type":"NEGATIVE"}'); exception when raise_exception then denied:=true; end;
 perform pg_temp.le_assert('event ID collision cannot change meaning',denied);
 denied:=false; begin perform public.le_command('outcome',p||'{"event_type":"WON","external_event_id":"fake-won"}'); exception when raise_exception then denied:=true; end;
 perform pg_temp.le_assert('WON requires payment integration',denied);
 perform pg_temp.le_assert('positive reply holds company',exists(select 1 from lead_engine.company_blocks where company_id=c and reason='POSITIVE' and active));
 a:=public.le_command('demo_payload',jsonb_build_object('company_id',c));
 perform pg_temp.le_assert('demo handoff retains identity and requires QA',a->>'company_id'=c::text and a->>'lead_status'='HOT_LEAD' and not (a->>'publish_ready')::boolean);
 denied:=false; begin perform public.le_command('demo_payload',jsonb_build_object('company_id',c2)); exception when raise_exception then denied:=true; end;
 perform pg_temp.le_assert('no demo trigger without positive interest',denied);
 perform pg_temp.le_assert('all private tables have RLS',not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='lead_engine' and c.relkind='r' and not c.relrowsecurity));
 perform pg_temp.le_assert('anon RPC denied',not has_function_privilege('anon','public.le_command(text,jsonb)','EXECUTE'));
 perform pg_temp.le_assert('authenticated RPC denied',not has_function_privilege('authenticated','public.le_command(text,jsonb)','EXECUTE'));
 perform pg_temp.le_assert('no security definer functions',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='lead_engine' and p.prosecdef));
end $$;
-- Actual service_role execution, not only a catalog permission check.
set local role service_role;
select public.le_command('ingest','{"source":"__le_service_test","external_id":"service-test","source_url":"https://service.invalid","company_name":"Service role test","website":"https://service.invalid"}');
reset role;
select pg_temp.le_assert('service-role API execution',exists(select 1 from lead_engine.companies where domain='service.invalid'));
do $$ declare denied boolean:=false; begin
 set local role anon;
 begin perform public.le_command('status'); exception when insufficient_privilege then denied:=true; end;
 reset role;
 perform pg_temp.le_assert('actual anonymous invocation blocked',denied);
end $$;
select jsonb_build_object('passed',count(*),'tests',jsonb_agg(name order by name)) as test_report from le_test_results;
