"use client";

import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowDown,Plus,Phone,Menu,X,Pause,Play,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';

const projects=[
 {name:'Een boerderij. Een nieuw hoofdstuk.',place:'Hellerweg',type:'Houtwerk & buitenschilderwerk',image:'/images/hellerweg.jpg',url:'https://www.bonke.nl/projecten/boederij-hellerweg/',text:'Bij deze boerderij verzorgde Bonke het schilderwerk van de houten gevel. Van inspectie en plaatselijke houtrotreparatie tot het voorbereiden en aflakken van het houtwerk.'},
 {name:'Samen zorgen voor de straat.',place:'In de Groene Bogen · Enschede',type:'Wijkgericht onderhoud',image:'/images/groene-bogen.jpg',url:'https://www.bonke.nl/projecten/de-groene-bogen-enschede/',text:'In de Groene Bogen stemt Bonke het onderhoud met verschillende huiseigenaren af. Samen met de buurt ontstaat een plan voor onderhoud en nieuw schilderwerk.'},
 {name:'Karakter verdient aandacht.',place:'Restaurant Loetje · Enschede',type:'Binnen- & buitenschilderwerk',image:'/images/loetje.jpg',url:'https://www.bonke.nl/projecten/restaurant-loetje/',text:'Voor Trebbe werkte Bonke aan het karakteristieke pand in het Volkspark: schilderwerk binnen en buiten, airless spuitwerk en wandafwerking.'}
];
const steps=[['Eerst uw verhaal.','Wat wilt u met uw woning? Blijven wonen, verhuren of verkopen: uw plannen vormen het vertrekpunt.'],['Dan een helder beeld.','We inspecteren de woning en adviseren welke werkzaamheden nodig zijn, met inzicht in de bijbehorende kosten.'],['Vakwerk aan huis.','Na afstemming gaan we aan het werk. Schilderwerk en onderhoud, met de aandacht die uw woning verdient.'],['Ook de jaren hierna.','Na het werk kunt u kiezen voor een meerjarenonderhoudsadvies. Zo houdt u zicht op volgend onderhoud.']];
const services=[['01','Schilderwerk','Binnen én buiten. Van een frisse wand tot het beschermen van kozijnen en gevelhout.'],['02','Hout- & betonreparatie','Een verzorgde afwerking begint bij een goede ondergrond. We kijken naar herstel waar dat nodig is.'],['03','Beglazing','Glaswerk als onderdeel van het onderhoud van uw woning. Bespreek bij de inspectie wat uw huis nodig heeft.'],['04','Wanden, vloeren & gevels','Ook voor stukadoorswerk, kunststofvloeren en gevelreiniging kunt u bij Bonke terecht.']];
export default function Home(){
 const [menu,setMenu]=useState(false),[contact,setContact]=useState(false),[project,setProject]=useState<number|null>(null),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(true),[prepared,setPrepared]=useState(false),[mail,setMail]=useState('');
 const video=useRef<HTMLVideoElement>(null),hero=useRef<HTMLElement>(null),progress=useRef<HTMLDivElement>(null);
 useEffect(()=>{const mq=window.matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(mq.matches);change();mq.addEventListener('change',change);const onScroll=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;if(progress.current)progress.current.style.transform=`scaleX(${max?window.scrollY/max:0})`;if(hero.current&&!mq.matches)hero.current.style.setProperty('--drift',`${Math.min(window.scrollY*.13,90)}px`)};window.addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>{mq.removeEventListener('change',change);window.removeEventListener('scroll',onScroll)}},[]);
 useEffect(()=>{if(!video.current)return;if(paused||reduced)video.current.pause();else video.current.play().catch(()=>setPaused(true))},[paused,reduced]);
 const ask=()=>{setMenu(false);setPrepared(false);setContact(true)};
 const CTA=({label='Vraag onderhoudsadvies',className=''}:{label?:string;className?:string})=><button className={`cta ${className}`} onClick={ask}>{label}<ArrowUpRight size={21}/></button>;
 return <>
 <a className="skip" href="#inhoud">Ga naar inhoud</a><div className="reading-progress" ref={progress}/>
 <header className="header"><a href="#" aria-label="Bonke, naar boven"><img className="logo" src="/images/logo.webp" alt="Bonke & Zn. — sinds 1924" width="2050" height="331"/></a><nav aria-label="Hoofdnavigatie"><a href="#aanpak">Onze aanpak</a><a href="#projecten">Ons werk</a><a href="#diensten">Wat we doen</a></nav><button className="header-cta" onClick={ask}>Laten we kennismaken <ArrowUpRight size={18}/></button><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label={menu?'Menu sluiten':'Menu openen'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
 {menu&&<nav className="mobile-nav" aria-label="Mobiel menu">{[['Onze aanpak','aanpak'],['Ons werk','projecten'],['Wat we doen','diensten'],['Ervaringen','ervaringen']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}<ArrowUpRight/></a>)}<CTA/></nav>}
 <main id="inhoud">
 <section className="hero" ref={hero} aria-labelledby="hero-title"><div className="hero-top"><span className="eyebrow">BONKE PLANMATIG ONDERHOUD</span><span className="hero-location">Voor particulieren · vanuit Enschede</span></div><div className="hero-copy"><h1 id="hero-title">Goed voor<br/>uw huis.<br/><em>Fijn voor u.</em></h1><p>Een huis om van te genieten.<br/>Met schilderwerk en onderhoud dat vooruitkijkt.</p><CTA className="orange"/><span className="cta-note">Vrijblijvend. We beginnen bij uw wensen.</span></div><div className="hero-art"><img src="/images/hero.webp" alt="" width="1600" height="1000" fetchPriority="high"/><video ref={video} muted loop playsInline preload="none" poster="/images/hero.webp" aria-hidden="true"><source src="/images/hero.mp4" type="video/mp4"/></video><span className="art-label">AANDACHT, LAAG VOOR LAAG.</span><button className="motion-control" onClick={()=>setPaused(!paused)} aria-label={reduced?'Animatie uit vanwege bewegingsvoorkeur':paused?'Animatie afspelen':'Animatie pauzeren'} disabled={reduced}>{paused||reduced?<Play size={16}/>:<Pause size={16}/>}</button></div><div className="hero-bottom"><span>Een familiebedrijf. Sinds 1924.</span><a href="#aanpak">Ontdek de rust van een plan <ArrowDown size={18}/></a><span className="hero-index">01 — 06</span></div></section>
 <div className="assurance"><span><Check/> Eén aanspreekpunt</span><span><Check/> Inzicht in onderhoudskosten</span><span><Check/> Aandacht voor vandaag én later</span></div>
 <section className="intro section" id="aanpak"><div className="section-label"><span>01 / MEER DAN EEN MOOIE LAAG</span><span>Een plan geeft rust.</span></div><div className="intro-grid"><h2>U woont.<br/>Wij kijken<br/><span className="blue-text">vooruit.</span></h2><div className="intro-right"><p className="lead">Uw huis heeft aandacht nodig. Maar liever volgens een plan dan pas wanneer het echt moet.</p><p>Met planmatig onderhoud krijgt u overzicht: wat heeft uw woning nodig, wanneer pakken we het aan en welke kosten horen daarbij? Samen brengen we dat in kaart.</p><a className="text-link" href="#stappen">Zo werkt het <ArrowDown size={19}/></a></div></div><div className="mini-facts"><div><strong>1924</strong><span>Het jaar waarin Bonke begon</span></div><div><strong>Uw huis</strong><span>Het vertrekpunt van ons advies</span></div><div><strong>Één plan</strong><span>Overzicht voor de komende jaren</span></div></div></section>
 <section className="projects section" id="projecten"><div className="section-label"><span>02 / WERK OM OP TERUG TE KIJKEN</span><span>Projecten van Bonke</span></div><div className="section-heading"><h2>Dat ziet u.<br/><em>Dat blijft.</em></h2><p>Van een houten boerderijgevel tot een hele buurt.<br/>Bekijk waar Bonke aan heeft gewerkt.</p></div><div className="project-gallery">{projects.map((p,i)=><button className={`project project-${i}`} key={p.place} onClick={()=>setProject(i)}><div className="project-image"><img src={p.image} alt={p.place+' — uitgevoerd werk van Bonke'} width="1120" height="844" loading="lazy"/><span className="project-number">0{i+1}</span><span className="project-open"><ArrowUpRight/></span></div><span className="project-meta">{p.type}</span><h3>{p.name}</h3><span className="project-place">{p.place}</span></button>)}</div><p className="source-note">Projecten en fotografie: Bonke & Zn. Bekijk de projectbeschrijving voor de oorspronkelijke bron.</p></section>
 <section className="process section" id="stappen"><div className="process-title"><span className="eyebrow">03 / VAN EERSTE GESPREK TOT LATER</span><h2>Een helder plan.<br/><em>In vier stappen.</em></h2><p>Geen woning is hetzelfde.<br/>Dus luisteren we voordat we beginnen.</p><CTA className="orange"/></div><div className="steps">{steps.map(([title,description],i)=><article key={title}><span className="step-number">0{i+1}</span><div><h3>{title}</h3><p>{description}</p></div><span className="step-line"/></article>)}</div></section>
 <section className="services section" id="diensten"><div className="section-label"><span>04 / ALLES BEGINT BIJ AANDACHT</span><span>Van ondergrond tot afwerking</span></div><div className="services-grid"><div><h2>Mooi aan<br/>de buitenkant.<br/><em>Goed eronder.</em></h2><p>We kijken verder dan verf alleen.<br/>Samen bepalen we wat nodig is.</p></div><div className="service-list">{services.map(([n,title,description],i)=><details key={n} open={i===0}><summary><span>{n}</span><h3>{title}</h3><Plus size={22}/></summary><p>{description}</p></details>)}</div></div></section>
 <section className="neighbours"><img src="/images/groene-bogen.jpg" alt="Woningen in de Groene Bogen in Enschede" width="1120" height="844" loading="lazy"/><div><span className="eyebrow">GOED VOOR HET HELE STRAATJE</span><h2>Samen met<br/>de buren?<br/><em>Goed idee.</em></h2><p>Stem het schilderonderhoud samen af. Met wijkgericht onderhoud combineert Bonke werkzaamheden in de buurt. Dat helpt efficiënt plannen en beperkt transport.</p><CTA label="Bespreek de mogelijkheden"/></div></section>
 <section className="reviews section" id="ervaringen"><div className="section-label"><span>05 / ERVARINGEN MET BONKE</span><span>Een keuze maakt u met vertrouwen.</span></div><div className="reviews-grid"><h2>Bekijk het werk.<br/>Lees de<br/><em>ervaringen.</em></h2><div className="rating-panel"><span className="eyebrow">PUBLIEKE BEOORDELING</span><div className="rating"><strong>4,3</strong><span>/ 5</span></div><p>12 Google-reviews, zoals vermeld op TrustusFix.</p><a className="text-link" href="https://trustusfix.com/vakmensen/3646" target="_blank" rel="noopener noreferrer">Bekijk de reviewvermelding <ArrowUpRight size={20}/></a><span className="source-note">Bron: TrustusFix · geraadpleegd 9 september 2026.<br/>De beoordeling is niet rechtstreeks bij Google geverifieerd.</span></div></div></section>
 <section className="faq section"><div><span className="eyebrow">NOG EVEN DIT</span><h2>Goede vragen.<br/><em>Heldere antwoorden.</em></h2></div><div>{[['Moet ik direct een onderhoudsplan afsluiten?','Nee. Het begint met uw wensen en een inspectie. Ook voor een eenmalige schilderbeurt kunt u bij Bonke terecht. Na uitvoering kunt u kiezen voor meerjarenonderhoudsadvies.'],['Wat kost het onderhoud van mijn huis?','Dat hangt af van uw woning, de staat van het hout- en schilderwerk en de werkzaamheden. Na inspectie kan Bonke adviseren over het werk en de kosten. Op deze pagina wordt daarom geen vaste prijs beloofd.'],['Kan ik samen met mijn buren onderhoud laten doen?','Ja, Bonke biedt wijkgericht onderhoud. Bespreek uw wijk en plannen met Bonke om te kijken welke mogelijkheden en planning er zijn.'],['Wat bespreken we tijdens het eerste contact?','Uw woning, uw wensen en uw toekomstplannen. U hoeft vooraf nog niet precies te weten welk onderhoud nodig is.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div></section>
 <section className="contact section" id="contact"><div className="section-label"><span>06 / GOED ONDERHOUD BEGINT MET EEN GESPREK</span><span>Bonke & Zn. · Enschede</span></div><div className="contact-main"><h2>Uw huis.<br/><em>Onze aandacht.</em></h2><div><p>Vertel wat er speelt.<br/>Samen kijken we vooruit.</p><CTA label="Vraag vrijblijvend onderhoudsadvies" className="dark"/><a className="phone-link" href="tel:+31534318809"><Phone size={18}/> Liever bellen? 053 – 431 88 09</a></div></div></section>
 </main><footer><div className="footer-main"><img src="/images/logo.webp" alt="Bonke & Zn." width="2050" height="331"/><div><strong>Kom gerust in contact.</strong><a href="mailto:schildersbedrijf@bonke.nl">schildersbedrijf@bonke.nl</a><span>Twekkeler-Es 41<br/>7547 ST Enschede</span></div><a href="#" className="back-top" aria-label="Terug naar boven"><ArrowUpRight/></a></div><div className="footer-bottom"><span>Onafhankelijk demo-ontwerp door De Website Dokter.</span><a href="https://www.bonke.nl/" target="_blank" rel="noopener noreferrer">Oorspronkelijke website <ArrowUpRight size={14}/></a><span>Hero: gegenereerde conceptvisual.</span></div></footer>
 <Dialog open={contact} onOpenChange={setContact}><DialogContent className="contact-dialog" showCloseButton={false}><DialogClose className="dialog-close" aria-label="Sluiten"><X/></DialogClose><span className="eyebrow">VRIJBLIJVEND ONDERHOUDSADVIES</span><DialogTitle className="dialog-title">Vertel ons over<br/>uw woning.</DialogTitle><DialogDescription>Dit is een demo. Uw gegevens worden niet opgeslagen of automatisch verzonden. U kunt hieronder een e-mail opstellen.</DialogDescription>{prepared?<div className="prepared"><Check size={32}/><h3>Uw bericht staat klaar.</h3><p>Open uw e-mailprogramma, controleer de inhoud en verstuur het zelf naar Bonke.</p><a className="cta orange" href={mail}>Open de conceptmail <ArrowUpRight size={20}/></a><button className="text-link" onClick={()=>setPrepared(false)}>Terug naar het formulier</button></div>:<form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const body=`Beste Bonke,\n\nIk ontvang graag vrijblijvend onderhoudsadvies.\n\nNaam: ${d.get('name')}\nE-mail: ${d.get('email')}\nWoonplaats: ${d.get('city')}\n\nMijn vraag:\n${d.get('message')}\n\nMet vriendelijke groet,\n${d.get('name')}`;setMail('mailto:schildersbedrijf@bonke.nl?subject='+encodeURIComponent('Aanvraag onderhoudsadvies')+'&body='+encodeURIComponent(body));setPrepared(true)}}><label>Uw naam<input required name="name" autoComplete="name" maxLength={120}/></label><div className="form-row"><label>E-mailadres<input required type="email" name="email" autoComplete="email" maxLength={200}/></label><label>Woonplaats<input required name="city" autoComplete="address-level2" maxLength={120}/></label></div><label>Waar kunnen we mee helpen?<textarea name="message" rows={3} required maxLength={3000} placeholder="Bijvoorbeeld: onderhoud aan onze houten kozijnen…"/></label><button className="cta orange" type="submit">Stel mijn e-mail op <ArrowUpRight size={20}/></button><span className="source-note">Er wordt op deze stap niets verstuurd.</span></form>}</DialogContent></Dialog>
 <Dialog open={project!==null} onOpenChange={open=>{if(!open)setProject(null)}}><DialogContent className="project-dialog" showCloseButton={false}>{project!==null&&<><DialogClose className="dialog-close" aria-label="Sluiten"><X/></DialogClose><img src={projects[project].image} alt={projects[project].place} width="1120" height="844"/><span className="eyebrow">{projects[project].type}</span><DialogTitle className="dialog-title">{projects[project].name}</DialogTitle><DialogDescription>{projects[project].text}</DialogDescription><a className="text-link" href={projects[project].url} target="_blank" rel="noopener noreferrer">Bekijk het oorspronkelijke project <ArrowUpRight size={18}/></a></>}</DialogContent></Dialog>
 </>
}
